/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Items {
  checked: Generated<number>;
  created_at: Generated<number>;
  id: string;
  last_checked_at: number | null;
  name: string;
}

export interface ListMetadata {
  name: string;
}

export interface DB {
  items: Items;
  list_metadata: ListMetadata;
}
