/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Operations {
  client_created_at: number;
  id: string;
  payload: string;
  server_committed_at: number | null;
  type: string;
}

export interface DB {
  operations: Operations;
}
